add Mac keymap
guylabs/intellij-idea-keymap pull request #7
Opened 2016-09-03 18:21 UTC by 5pid

2016-09-24 07:01 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'left': 'tree-view:collapse-directory'
This shortcut already works out of the box in Atom. I would remove it here such that we just have the shortcuts which are different between IDEA and Atom.

This is also the case for `right` and `enter`.

2016-09-24 07:04 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-c': 'tree-view:copy'
This shortcut already works out of the box in Atom. I would remove it here such that we just have the shortcuts which are different between IDEA and Atom.

This is also the case for:

* `cmd-x`
* `cmd-v`
* `backspace`

The `delete` I cannot test as I only have the laptop keyboard. ;)

2016-09-24 07:06 UTC, guylabs requested changes
Hi @5pid 

thanks a lot for the PR! Really appreciate such contributions. I just added some review comments. Could you maybe go through them and adapt these such that I can merge it with the master and release a new version?

If you have any questions please ask.

Thanks and regards,

Guy

2016-09-24 07:06 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-]': 'pane:show-next-item'
This shortcut already works out of the box in Atom. I would remove it here such that we just have the shortcuts which are different between IDEA and Atom.

2016-09-24 07:06 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-[': 'pane:show-previous-item'
This shortcut already works out of the box in Atom. I would remove it here such that we just have the shortcuts which are different between IDEA and Atom.

2016-09-25 08:54 UTC, 5pid commented
@guylabs 
Thanks for reviews.
I fixed shortcut refer to your comments
Please check commit.

2016-09-25 08:56 UTC, 5pid commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-]': 'pane:show-next-item'
deleted line.

2016-09-25 10:21 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-]': 'pane:show-next-item'
This line is still in and is not deleted. Could you also delete this one?

2016-09-25 10:21 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-[': 'pane:show-previous-item'
This line is still in and is not deleted. Could you also delete this one?

2016-09-25 10:22 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-\\': 'unset!' # cancel the tree-view shortcut
I would not unset the standard shortcuts as the shortcuts for idea should just be an addition to the default ones. Could you maybe remove all the `unset!` shortcuts?

2016-09-25 10:22 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'ctrl-shift-C': 'unset!'
I would not unset the standard shortcuts as the shortcuts for idea should just be an addition to the default ones. Could you maybe remove all the `unset!` shortcuts?

2016-09-25 10:22 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'f2': 'unset!'
I would not unset the standard shortcuts as the shortcuts for idea should just be an addition to the default ones. Could you maybe remove all the `unset!` shortcuts?

2016-09-25 10:23 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-k cmd-b': 'unset!' # cancel the tree-view shortcut
I would not unset the standard shortcuts as the shortcuts for idea should just be an addition to the default ones. Could you maybe remove all the `unset!` shortcuts?

2016-09-25 10:24 UTC, guylabs commented on keymaps/intellij-idea-keymap.cson
> +  'a': 'unset!'
I would not unset the standard shortcuts as the shortcuts for idea should just be an addition to the default ones. Could you maybe remove all the `unset!` shortcuts?

2016-09-25 10:26 UTC, guylabs requested changes
Hi @5pid 

thanks for the quick changes but there are still some lines which need to be removed and please also remove all the `unset!` shortcuts as we do not want to remove the standard Atom shortcuts.

After these changes I can merge it and release a newer version.

Thanks and regards,

Guy

2016-09-29 01:25 UTC, 5pid commented on keymaps/intellij-idea-keymap.cson
> +  'cmd-shift-]': 'pane:show-next-item'
Sorry. It is my mistake.

2016-09-29 01:33 UTC, 5pid commented
@guylabs 
Sorry. my mistake.
I deleted that missing codes.
Thanks for reviews.

2016-09-29 06:07 UTC, guylabs approved these changes

2016-09-29 06:09 UTC, merged